# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_posttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='PostType',
            field=models.BooleanField(default=True, verbose_name=b'PostType:'),
            preserve_default=False,
        ),
    ]
