# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_posttype_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttype',
            name='PostType',
            field=models.BooleanField(verbose_name=b'Type:'),
        ),
    ]
