# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161225_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttype',
            old_name='PostType',
            new_name='PType',
        ),
    ]
