# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161225_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostType',
            new_name='Type',
        ),
    ]
