# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161225_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
