# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='post',
            name='ptype',
            field=models.BooleanField(default=True, verbose_name=b'Type:'),
            preserve_default=False,
        ),
    ]
