# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20161225_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ptype',
            field=models.CharField(choices=[(b'CT', b'Content'), (b'WS', b'WorkSpace')], default=b'CT', max_length=2),
        ),
    ]
