# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20161225_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ptype',
            new_name='kind',
        ),
    ]
